spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${database}
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email}
    password: ${password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  key: $2a$10$RSmLI.skBXCp8ldBCA/6.uET.eHuY6/RiEafTBtbr0rtvQsPc8oS2
expiration:
  time: 86400000

#  Corn expression to add the working days of the students five day of week.
corn:
  expression: "* 0 9 * * 1-5 ?"
